### ISSUE TITLE
Configuration problem with Pandora FMS

### ISSUE THREAD

**Issue by danfossi** [rchakode/realopinsight#21] opened 2019-12-09 12:00 UTC
Good morning,
we are trying to configure RealOpInsight (OVA Image)  for use with Pandora FMS .. unfortunately some steps of the official guide are not very clear.

Assuming the pandora server is configured with:

IP: 192.168.1.60
User: admin
Pass: password
Api-Key: 1234

What are the parameters to insert in the fields: Monitor URL Base URL and Auth String?

Actually (as suggested [in the doc](http://realopinsight.com/docs/monitoring-data-sources/)) I've tried:

Monitor URL Base URL: https://192.168.1.60/pandora_console/include/api.php
Auth String: admin:password:1234

And:

Monitor URL Base URL: https://192.168.1.60/pandora_console/
Auth String: admin:password:1234

And:

Monitor URL Base URL: https://192.168.1.60/
Auth String: admin:password:1234

But without success (both with "Don't verify SSL certificate" active or inactive).

-- 
Pandora's APIs are working fine, if from RealOpInsight VM I type:

curl -k "https://192.168.1.60/pandora_console/include/api.php?op=get&op2=test&apipass=1234&user=admin&pass=password"

I get: 

OK, v7.0NG.737, PC190731

Therefore the indicated parameters are correct and the APIs can be correctly accessed.

**Comment by rchakode** [comment] 2019-12-09 19:47
Hi @danfossi,
Which error did you have?
Some screenshot to share? You may also need to take a look a the log files in /opt/realopinsight/log/

**Comment by rchakode** [comment] 2019-12-09 19:51
By the way, it API endpoint would be: https://192.168.1.60/include/api.php

For more details, see: https://pandorafms.com/docs/index.php?title=Pandora:Documentation_en:Annex_ExternalAPI

**Comment by danfossi** [comment] 2019-12-11 09:26
Hi @rchakode,
thanks for the quick reply, I did some tests but no luck.

I have double-checked:
* Pandora FMS Version: 7.0NG.737 (Build: 190731)
* APIs ACL in Pandora
* User, Pass and API-Key

Here the input in config page:
![immagine](https://user-images.githubusercontent.com/3583794/70607737-4ebf6d00-1bff-11ea-844b-14a3a3676dbd.png)

Here the output of log file:
```
2019-12-11T03:34:53 [info] Using PostgreSQL database

2019-12-11T03:35:19 [info] Using PostgreSQL database

2019-12-11T03:35:23 [info] admin logged in. Session Id: 16Tap7J2QBtlfuwY

2019-12-11T03:35:43 [debug] No service selected

2019-12-11T03:35:56 [warn] Invalid or incompleted view with root

2019-12-11T03:38:56 [warn] failed connecting to source (Cannot load data points for unknown data 
source: 99)

2019-12-11T03:41:37 [warn] failed connecting to source (Cannot load data points for unknown data source: 99)

2019-12-11T03:41:48 [warn] failed connecting to source (Cannot load data points for unknown data source: 99)

2019-12-11T03:41:55 [warn] failed connecting to source (Cannot load data points for unknown data source: 99)

2019-12-11T03:42:30 [warn] failed connecting to source (Cannot load data points for unknown data source: 99)
```

Here the output of curl from RealOpInsight server to Pandora FMS (so problem does not seem to be related to: API ACL or User/Pass/Key):

```
ubutnu@roistack:~$  curl -k "https://192.168.1.60/pandora_console/include/api.php?op=get&op2=test&apipass=1234&user=admin&pass=password"

OK,v7.0NG.737,PC190731
````

**Comment by rchakode** [comment] 2019-12-11 09:30
Did you click on `Add as new source`, and not on `Apply changes`?

**Comment by danfossi** [comment] 2019-12-11 09:33
yes, he proposes to choose a source ID, selecting 0 (or any other number) proposes the error in the attachment.

**Comment by rchakode** [comment] 2019-12-11 09:47
Weird, I'll check what is happening.

**Comment by danfossi** [comment] 2019-12-11 09:50
let me know if I can help by doing other tests, I have a backup of both VMs, so if we need to do some more invasive tests, it's not a problem.

**Comment by rchakode** [comment] 2019-12-11 10:07
The error message suggests
that the source ID has not been taken into account, what is actually a thing I cannot reproduce.

Which browser and version do you use?

**Comment by danfossi** [comment] 2019-12-11 10:40
Browser tested:
* Firefox 71.0 (64 bit)
* Firefox 70.0.1 (32 bit)
* Edge 44.18362
* IE11
* Chrome 78.0.3904

**Comment by rchakode** [comment] 2019-12-13 07:42
Hi @danfossi,
Just for your information, the investigation of this issue may have some delays due to the holidays of our contributors.

**Comment by danfossi** [comment] 2019-12-13 11:27
More info:
Just to be sure that the problem does not depend on the version of Pandora FMS (and to try to circumscribe the problem), I also tried to clone Pandora's VM and update to the last stable: 7.0NG.739 (Build: PC190930), unfortunately it has not solved.

**Comment by rchakode** [comment] 2020-01-04 19:31
Dear @danfossi,
Like us, we hope that you took some time relax during the end of year holidays. 
Unfortunately we were not able to further investigate this issue.

Now we went back to our daily routine :)

So after investigation, we're able to reproduce the issue. We'll work to fix it in our next release, which is expected in the very close weeks (likely by the end of January/begin of Febuary).
We're sorry for the inconvenience and will let you know when the fix will be released.

R.

**Comment by rchakode** [comment] 2020-01-04 19:50
Dear @danfossi,
In the meantime we have  workaround alternative to let you try our fix before the release.

Can you please try the following?

* Download the attached zip file
* Unzip the archive and copy the resulting binary at  `/opt/realopinsight/sbinrealopinsight-server` on your RealOpInsight machine. Please note that this should replace the existing binary. 
* Restart the service as follows `sudo systemctl restart realopinsight-server`

Let me known if that fix the issue.
R.
[realopinsight-server.zip](https://github.com/rchakode/realopinsight/files/4022341/realopinsight-server.zip)

**Comment by rchakode** [comment] 2020-10-25 05:44
The support of Pandora FMS is now deprecated.

**Closed by rchakode** 2020-10-25 05:44 UTC
